language: java
jdk:
  - openjdk8
env:
  - NODE_VERSION="9"
cache:
  directories:
    - "node_modules" # This will tell Travis CI to cache the dependencies
before_install:
  - nvm install $NODE_VERSION
script: npm run release # Here you could also run the build step of your application
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script # Run a custom deployment script which we will define below
    script: now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true